# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('account_type', models.CharField(blank=True, max_length=200, null=True)),
                ('other_info', models.CharField(blank=True, max_length=200, null=True)),
                ('access_token_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
