# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='oauth_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
