# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_app', '0003_account_oauth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('scheduling_type', models.CharField(choices=[('Schedule Manually', 'Schedule Mnaually'), ('KemiBox Scheduling', 'KemiBox Scheduling'), ('Post Now', 'Post Now')], max_length=200)),
                ('time_slot', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
                ('account', models.ManyToManyField(to='login_app.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Post')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.Group'),
        ),
    ]
