# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20180426_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_slot',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
