# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20180427_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20)),
                ('day_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Account')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Day')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduling_type',
            field=models.CharField(choices=[('Schedule Manually', 'Schedule Manually'), ('KemiBox Scheduling', 'KemiBox Scheduling'), ('Post Now', 'Post Now')], max_length=200),
        ),
    ]
