# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20180427_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduling_type',
            field=models.CharField(choices=[('Schedule Manually', 'Schedule Manually'), ('KemiBox Queue', 'KemiBox Queue'), ('Post Now', 'Post Now')], max_length=200),
        ),
        migrations.AddField(
            model_name='publishingtime',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Post'),
        ),
    ]
