# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_auto_20180427_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishingtime',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.Timeslot'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
