# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_auto_20180427_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['day_no']},
        ),
        migrations.AddField(
            model_name='post',
            name='no_of_publsih_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='total_publsihing_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='last_used_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='next_available_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
