# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0012_auto_20180429_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='oauth_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
