# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-29 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0013_token_oauth_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='access_token_info',
        ),
    ]
