# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0014_auto_20180429_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='access_token_secret',
        ),
        migrations.AddField(
            model_name='account',
            name='access_token_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.Token'),
        ),
    ]
